export enum UserRole {
  EFS_SBERASSIST_RMAP_USER = "EFS_SBERASSIST_RMAP_USER",
  EFS_SBERASSIST_RMAP_MANAGEMENT = "EFS_SBERASSIST_RMAP_MANAGEMENT",
  EFS_SBERASSIST_BASE = "EFS_SBERASSIST_BASE",
  EFS_SBERASSIST_MANAGER = "EFS_SBERASSIST_MANAGER",
  EFS_SBERASSIST_OPERATOR = "EFS_SBERASSIST_OPERATOR",
  EFS_SBERASSIST_ENGEENER = "EFS_SBERASSIST_ENGEENER",
  EFS_SBERASSIST_VIP = "EFS_SBERASSIST_VIP",
  EFS_SBERASSIST_KOORDINATOR = "EFS_SBERASSIST_KOORDINATOR",
  EFS_SBERASSIST_EMPLOYEE_CC = "EFS_SBERASSIST_EMPLOYEE_CC",
  EFS_SBERASSIST_CHIEF = "EFS_SBERASSIST_CHIEF",
}
